name: Trigger auto deployment for naar-marketplace

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/naar-marketplace-AutoDeployTrigger-a55ab0c2-3aae-4eae-8a91-b093ed2a0b4f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.NAARMARKETPLACE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.NAARMARKETPLACE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.NAARMARKETPLACE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: docker.io
          registryUsername: ${{ secrets.NAARMARKETPLACE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.NAARMARKETPLACE_REGISTRY_PASSWORD }}
          containerAppName: naar-marketplace
          resourceGroup: naar-rg
          imageToBuild: thedollmaster98/naar-marketplace:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


